services:
  ecommerce:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - ./data:/app/data
    ports:
      - 8000:8000
    restart: unless-stopped
    env_file:
      - .env
