name: Ecommerce App CI

on:
  push:
    branches:
      - main

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    env:
      DJANGO_SETTINGS_MODULE: core.settings
      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY || 'dummy-secret-key-for-testing' }}
      GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
      MODEL: ${{ secrets.MODEL }}
      IMAGE_NAME: lecturerhasan/ecommerce:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run migrations
        run: python manage.py migrate
      
      - name: Run tests
        run: python manage.py test

      - name: Build Docker image
        run: docker build -t $IMAGE_NAME .

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Push Docker image
        run: docker push $IMAGE_NAME